- src/main/org/codehaus/groovy/control/CompilationUnit.java
- src/main/org/codehaus/groovy/control/GenericsVisitor.java
- src/main/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/gls/generics/GenericsTest.groovy
> GROOVY-7865: Better error message and earlier detection of Generics errors

- src/main/org/codehaus/groovy/classgen/AsmClassGenerator.java
- src/test/groovy/bugs/Groovy8289Bug.groovy
PR based on Eric's suggested fix in the issue. Still needs a test.
> GROOVY-8289: STC and default value in ctor is causing debugging error

- src/main/java/org/codehaus/groovy/antlr/GroovySourceAST.java
- src/main/java/org/codehaus/groovy/vmplugin/v5/PluginDefaultGroovyMethods.java
- subprojects/groovy-groovydoc/src/main/java/org/codehaus/groovy/groovydoc/GroovyRootDoc.java
- subprojects/groovy-groovydoc/src/main/java/org/codehaus/groovy/tools/groovydoc/GroovyDocTemplateEngine.java
- subprojects/groovy-groovydoc/src/main/java/org/codehaus/groovy/tools/groovydoc/SimpleGroovyClassDoc.java
- subprojects/groovy-groovydoc/src/main/java/org/codehaus/groovy/tools/groovydoc/SimpleGroovyDoc.java
- subprojects/groovy-groovydoc/src/main/java/org/codehaus/groovy/tools/groovydoc/SimpleGroovyRootDoc.java
There's a lot to say about Groovydoc, but worst of all, its performance is terrible. This PR is an attempt to fix part of it.
Before my changes: https://scans.gradle.com/s/msfs2nf5mqmxw (3m35s)
After my changes: https://scans.gradle.com/s/a7pi5g6bb7bbu (53s)
@paulk-asert I'm leaving the review/merge to you as I spent already too much time on this. Given the improvements, I wouldn't mind a backport to 2.5!
> Optimize generation of Groovydoc

- gradle/eclipse.gradle
Tasks for cleaning generated files and folders.
Save actions for removing trailing spaces and organizing imports in editor.
> Add clean tasks and save actions to eclipse gradle setup

- gradle/eclipse.gradle
> Sort eclipse classpath entries by artifact name

- src/main/java/org/codehaus/groovy/control/CompilationUnit.java
- src/main/java/org/codehaus/groovy/tools/javac/JavaAwareCompilationUnit.java
- src/main/java/org/codehaus/groovy/tools/javac/JavaStubCompilationUnit.java
Additional cleanup for sub-types of ProcessingUnit
> Refactor and allow default CompilerConfiguration as parent allows

- gradle/pomconfigurer.gradle
- src/test/groovy/generated/AbstractGeneratedAstTestCase.groovy
- src/test/groovy/generated/AutoCloneGeneratedTest.groovy
- src/test/groovy/generated/AutoExternalizeGeneratedTest.groovy
- src/test/groovy/generated/BindableGeneratedTest.groovy
- src/test/groovy/generated/BuilderGeneratedTest.groovy
- src/test/groovy/generated/CanonicalGeneratedTest.groovy
- src/test/groovy/generated/ConstructorsGeneratedTest.groovy
- src/test/groovy/generated/DelegateGeneratedTest.groovy
- src/test/groovy/generated/GroovyObjectGeneratedTest.groovy
- src/test/groovy/generated/ImmutableGeneratedTest.groovy
- src/test/groovy/generated/IndexedPropertyGeneratedTest.groovy
- src/test/groovy/generated/PropertiesGeneratedTest.groovy
- src/test/groovy/generated/SortableGeneratedTest.groovy
- src/test/groovy/generated/VetoableGeneratedTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9164
> Add first batch of tests for @Generated. Relates to GROOVY-9164

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingSupport.java
- src/test/groovy/bugs/Groovy8609Bug.groovy
- src/test/groovy/bugs/Groovy9074.groovy
See comment in GROOVY-9074 for next step(s)
> GROOVY-9074: Allow chooseBestMethod to match "? super T"

- src/main/java/groovy/lang/Closure.java
- src/main/java/groovy/lang/ExpandoMetaClass.java
- src/main/java/groovy/lang/GroovyClassLoader.java
- src/main/java/groovy/lang/IntRange.java
- src/main/java/groovy/lang/MetaClassImpl.java
- src/main/java/groovy/lang/NumberRange.java
- src/main/java/groovy/lang/ObjectRange.java
- src/main/java/groovy/ui/GroovySocketServer.java
- src/main/java/groovy/util/PermutationGenerator.java
This is fixing some potential bugs from https://sonarcloud.io/dashboard?id=danielsun1106_groovy
@danielsun1106
> Fix potential bugs

- src/main/java/groovy/ui/GroovyMain.java
- src/main/java/org/codehaus/groovy/tools/FileSystemCompiler.java
Options added to following classes:
- `groovy.ui.GroovyMain`
- `org.codehaus.groovy.tools.FileSystemCompiler`
*also trivial code refactoring and replacing deprecated method*
> GROOVY-9228: CLI options for static compilation

- src/main/java/org/codehaus/groovy/classgen/asm/sc/StaticTypesMethodReferenceExpressionWriter.java
- src/main/java/org/codehaus/groovy/control/SourceUnit.java
> Minor refactoring: Refine collecting errors when generating bytecode for native method reference

- src/main/java/org/codehaus/groovy/ast/ClassNode.java
This change includes some basic formatting fixes (spaces around operators, etc.), which wasn't consistent in the original version. 
I also added a space that was missing in an error message.
> Minor: Improve code readability

- src/main/java/org/codehaus/groovy/antlr/AntlrParserPlugin.java
- src/main/java/org/codehaus/groovy/ast/AnnotationNode.java
- src/main/java/org/codehaus/groovy/reflection/CachedClass.java
- src/main/java/org/codehaus/groovy/reflection/stdclasses/CachedSAMClass.java
- src/main/java/org/codehaus/groovy/runtime/callsite/CallSiteArray.java
- src/main/java/org/codehaus/groovy/runtime/powerassert/AssertionRenderer.java
I found several optimizations while learning this code.
> Code optimization

- subprojects/groovy-groovysh/src/main/groovy/org/apache/groovy/groovysh/util/PackageHelperImpl.groovy
Reworked `PackageHelperImpl.getPackageNames(URL)` to handle IOException (parent of ZipException and FileNotFoundException) and InvalidPathException.  This should improve compatibility with Java 9+ for jars within jars.
See [https://issues.apache.org/jira/browse/GROOVY-9257](GROOVY-9257) for maven project that can be used to test this.
> GROOVY-9257: ZipException, FNFE -> IOException, InvalidPathException

- src/main/java/groovy/lang/GroovyClassLoader.java
- src/main/java/org/codehaus/groovy/classgen/asm/ClosureWriter.java
- src/main/java/org/codehaus/groovy/reflection/CachedClass.java
- src/main/java/org/codehaus/groovy/reflection/ClassInfo.java
- src/main/java/org/codehaus/groovy/reflection/ClassLoaderForClassArtifacts.java
- src/main/java/org/codehaus/groovy/runtime/DefaultGroovyMethods.java
- src/main/java/org/codehaus/groovy/runtime/metaclass/ClosureMetaClass.java
I found several code again that can be changed to a lambda expression.
> java 8 refacotor

- subprojects/groovy-json/src/main/java/groovy/json/DefaultJsonGenerator.java
- subprojects/groovy-json/src/main/java/org/apache/groovy/json/internal/CharSequenceValue.java
- subprojects/groovy-json/src/main/java/org/apache/groovy/json/internal/NumberValue.java
- subprojects/groovy-nio/src/main/java/org/apache/groovy/nio/extensions/NioExtensions.java
- subprojects/groovy-test/src/main/java/groovy/test/AllTestSuite.java
- subprojects/groovy-test/src/main/java/groovy/test/GroovyAssert.java
- subprojects/groovy-test/src/main/java/groovy/test/GroovyTestCase.java
- subprojects/groovy-test/src/main/java/groovy/test/GroovyTestSuite.java
Refactored some code about new java version.
--Make a contribution to groovy every day.
> Refactor code

- src/main/java/org/codehaus/groovy/transform/sc/StaticCompilationVisitor.java
- src/test/org/codehaus/groovy/classgen/asm/sc/MixedModeStaticCompilationTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9328
> GROOVY-9328: add outer class accessors to all outer classes

- src/main/java/org/codehaus/groovy/ast/tools/GenericsUtils.java
- src/test/groovy/transform/stc/LambdaTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9340
> GROOVY-9340: return type, not type redirect

- src/main/java/groovy/lang/MetaClassImpl.java
- src/main/java/org/codehaus/groovy/runtime/metaclass/ConcurrentReaderHashMap.java
Just my guess that this was the intention of the author(s).
> Make content of statements match indentation

- src/main/java/org/codehaus/groovy/classgen/VariableScopeVisitor.java
- src/test/groovy/bugs/Groovy9120.groovy
https://issues.apache.org/jira/browse/GROOVY-9120
> GROOVY-9120: check for local variable references within AIC

- src/main/java/org/apache/groovy/ast/tools/ExpressionUtils.java
- src/test/groovy/bugs/Groovy9336.groovy
https://issues.apache.org/jira/browse/GROOVY-9336
> GROOVY-9336: integer target type for shift RHS in constant initializer

- src/main/groovy/groovy/grape/GrapeIvy.groovy
https://issues.apache.org/jira/browse/GROOVY-9376
> GROOVY-9376: add grab/grape resolver to start of chain

- build.gradle
- src/main/java/org/codehaus/groovy/control/CompilerConfiguration.java
- src/main/java/org/codehaus/groovy/vmplugin/v7/Java7.java
- src/main/java/org/codehaus/groovy/vmplugin/v8/Java8.java
- src/spec/test/SyntaxTest.groovy
- src/test/gls/annotations/AnnotationTest.groovy
- src/test/groovy/lang/ScriptSourcePositionInAstTest.groovy
- src/test/groovy/lang/StripMarginTest.groovy
- src/test/org/codehaus/groovy/runtime/InterfaceConversionTest.groovy
- subprojects/tests-vm8/src/test/groovy/gls/annotations/vm8/AnnotationTest.groovy
Basic fixes required for 2.5.X to work on JDK14. Just one test (currently disabled) that needs further work but even that can possibly wait.
> GROOVY-9211: BUG! UNCAUGHT EXCEPTION on OpenJDK14-ea+8

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
And `gradle-legacy-osgi-plugin` to `0.0.3`.
> Update Gradle to 6.2.1

- src/main/java/org/codehaus/groovy/classgen/FinalVariableAnalyzer.java
- src/test/org/codehaus/groovy/classgen/FinalVariableAnalyzerTest.groovy
> GROOVY-9424: Incorrect handling of final variables within switch

- src/main/java/org/codehaus/groovy/tools/javac/JavaStubGenerator.java
- subprojects/groovy-console/src/main/groovy/groovy/console/ui/Console.groovy
- subprojects/groovy-console/src/main/groovy/groovy/console/ui/ConsoleActions.groovy
- subprojects/groovy-console/src/main/groovy/groovy/console/ui/view/BasicMenuBar.groovy
- subprojects/groovy-console/src/main/groovy/groovy/console/ui/view/MacOSXMenuBar.groovy
See https://issues.apache.org/jira/browse/GROOVY-9447
> GROOVY-9447: Add a parse tree viewer to groovy console

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/TypeInferenceSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9454
> GROOVY-9454: STC: check for instanceof type before using the field type

- src/main/java/org/codehaus/groovy/tools/javac/JavaStubGenerator.java
- src/test/org/codehaus/groovy/tools/stubgenerator/Groovy9462.groovy
https://issues.apache.org/jira/browse/GROOVY-9462
> GROOVY-9462: print placeholder using getUnresolvedName()

- subprojects/groovy-console/build.gradle
- subprojects/groovy-console/src/main/groovy/groovy/console/ui/Console.groovy
- subprojects/groovy-console/src/main/groovy/groovy/console/ui/ConsoleActions.groovy
- subprojects/groovy-console/src/main/groovy/groovy/console/ui/view/BasicMenuBar.groovy
- subprojects/groovy-console/src/main/groovy/groovy/console/ui/view/MacOSXMenuBar.groovy
See https://issues.apache.org/jira/browse/GROOVY-9468
Run the same code twice: 
```java
public class HelloWorld {
public static void main(String[] args) {
System.out.println("Hello, world!");
}
}
```
* `Ctrl + Alt + R` to run as Java for the first time
* `Ctrl + R` to run as Groovy for the second time
> GROOVY-9468: Support running as Java code in the Groovy console

- src/main/java/groovy/inspect/package.html
Fix for https://sonarcloud.io/project/issues?id=apache_groovy&open=AXD-_jqMDC9Fk2pZiWTt&resolved=false&types=BUG
Added missing tag and attribute in package.html
> Added DOCTYPE tag and "lang" attribute

- src/main/java/groovy/lang/ExpandoMetaClass.java
- src/main/java/groovy/lang/MetaClassImpl.java
- src/main/java/org/codehaus/groovy/runtime/metaclass/ClosureMetaClass.java
- src/test/groovy/bugs/Groovy9487.groovy
See https://issues.apache.org/jira/browse/GROOVY-9487
> GROOVY-9487: Update and check if initialized via same field of metaclass

- src/main/java/groovy/lang/MetaClassImpl.java
- src/main/java/org/codehaus/groovy/tools/LoaderConfiguration.java
Sorry, my last pull request missed two places. :(
> Switch to faster String#indexOf method taking a char parameter.

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/ArraysAndCollectionsSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9517
> GROOVY-9517: use inferred right expression type for array checks

- src/main/java/groovy/util/GroovyScriptEngine.java
- src/test/groovy/util/GroovyScriptEngineReloadingTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9526
> GROOVY-9526: Failed to reload classes with generic parameters

- src/main/java/org/codehaus/groovy/classgen/AsmClassGenerator.java
- src/test/gls/innerClass/InnerClassTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9501
> GROOVY-9501: enable access to static, non-final, subclassed-outer fields

- src/main/java/org/codehaus/groovy/syntax/ASTHelper.java
Simple Sonar, e.g: https://sonarcloud.io/project/issues?id=apache_groovy&issues=AXIngM_YBdjO4dFcRg1s&open=AXIngM_YBdjO4dFcRg1s
> Sonar: Replace the type specification in this constructor call with the diamond operator ("<>")

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/TypeInferenceSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-7549
> GROOVY-7549: STC: if "=" RHS type is inaccessible, revert to origin type

- src/main/java/org/codehaus/groovy/classgen/asm/BinaryExpressionHelper.java
- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/lang/ClosureResolvingTest.groovy
- src/test/groovy/transform/stc/ClosuresSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-7701
> GROOVY-7701: do not cast RHS before LHS of assignment is visited

- src/main/java/org/codehaus/groovy/classgen/InnerClassCompletionVisitor.java
- src/test/gls/innerClass/InnerClassTest.groovy
InnerClassCompletionVisitor overwrote user's methodMissing or propertyMissing with synthetic dispatcher.
https://issues.apache.org/jira/browse/GROOVY-8274
> GROOVY-8274: allow user-supplied methodMissing in non-static inner class

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/BugsSTCTest.groovy
- src/test/groovy/transform/stc/DelegatesToSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9604
> GROOVY-9604: STC: add support for accessing additional closure methods and properties

- src/main/java/org/codehaus/groovy/classgen/VariableScopeVisitor.java
- src/test/gls/innerClass/InnerClassTest.groovy
- src/test/groovy/transform/stc/FieldsAndPropertiesSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9598
> GROOVY-9598: account for static modifier when checking for outer members

- src/main/java/groovy/lang/MetaClassImpl.java
- src/test/groovy/bugs/Groovy9615.groovy
https://issues.apache.org/jira/browse/GROOVY-4945
https://issues.apache.org/jira/browse/GROOVY-9615
> GROOVY-4945, GROOVY-9615: call invokeMissingMethod on MetaClass of super

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/ClosureParamTypeInferenceSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9597
> GROOVY-9597: STC: update receiver after method selection

- src/main/java/org/codehaus/groovy/ast/ClassNode.java
https://issues.apache.org/jira/browse/GROOVY-9634
> GROOVY-9634: use getDeclaredMethods(String), not getMethods(String)

- src/main/java/org/codehaus/groovy/classgen/asm/sc/StaticTypesCallSiteWriter.java
- src/main/java/org/codehaus/groovy/transform/sc/StaticCompilationVisitor.java
- src/test/org/codehaus/groovy/classgen/asm/sc/bugs/Groovy7276.groovy
- src/test/org/codehaus/groovy/classgen/asm/sc/bugs/Groovy7304.groovy
https://issues.apache.org/jira/browse/GROOVY-7304
> GROOVY-7304: handle private field access from closure for ++x and x++

- src/main/java/org/codehaus/groovy/classgen/AsmClassGenerator.java
- src/main/java/org/codehaus/groovy/transform/sc/transformers/BinaryExpressionTransformer.java
- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/FieldsAndPropertiesSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9653
> GROOVY-9653: SC: improve classgen for multiple setter method candidates

- src/main/java/org/codehaus/groovy/transform/sc/transformers/BinaryExpressionTransformer.java
- src/main/java/org/codehaus/groovy/transform/sc/transformers/VariableExpressionTransformer.java
- src/test/groovy/transform/stc/ClosuresSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9652
> GROOVY-9652: after "x" to "delegate.x", don't make "delegate.delegate.x"

- src/main/java/org/codehaus/groovy/transform/trait/TraitReceiverTransformer.java
- src/test/org/codehaus/groovy/transform/traitx/TraitASTTransformationTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9386
> GROOVY-9386: traits: do not transform dynamic variable within closure

- src/main/java/org/codehaus/groovy/transform/trait/SuperCallTraitTransformer.java
- src/test/org/codehaus/groovy/transform/traitx/TraitASTTransformationTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9256
> GROOVY-9256: process closure expressions for Trait.super.name transforms

- src/main/java/org/codehaus/groovy/transform/trait/SuperCallTraitTransformer.java
- src/test/org/codehaus/groovy/transform/traitx/TraitASTTransformationTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9672
> GROOVY-9672: traits: replace "this" argument with "Type" for static super call

- src/main/java/org/codehaus/groovy/control/StaticImportVisitor.java
- src/test/groovy/bugs/Groovy8816.groovy
- src/test/groovy/bugs/Groovy9691.groovy
https://issues.apache.org/jira/browse/GROOVY-9691
> GROOVY-9691: don't transform MCE to SMCE within closure outside of special ctor call

- src/main/java/org/codehaus/groovy/transform/trait/Traits.java
- src/test/org/codehaus/groovy/transform/traitx/TraitASTTransformationTest.groovy
https://issues.apache.org/jira/browse/GROOVY-8000
> GROOVY-8000: pass interface with adjusted generics to recursive collect

- subprojects/parser-antlr4/src/main/java/org/apache/groovy/parser/antlr4/AstBuilder.java
https://issues.apache.org/jira/browse/GROOVY-9692
> GROOVY-9692: "call" method call for non-string expression w/ closure arg

- src/main/java/org/codehaus/groovy/classgen/asm/sc/StaticTypesBinaryExpressionMultiTypeDispatcher.java
- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/org/codehaus/groovy/classgen/asm/sc/bugs/Groovy7361Bug.groovy
and drop extra visitation for "putAt" method call transformation
https://issues.apache.org/jira/browse/GROOVY-9699
> GROOVY-9699: SC: reposition checkOrMarkPrivateAccess for field reference

- src/main/java/org/codehaus/groovy/transform/sc/transformers/BinaryExpressionTransformer.java
- src/test/org/codehaus/groovy/classgen/asm/sc/FieldsAndPropertiesStaticCompileTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9700
> GROOVY-9700: SC: transform variable assignment to direct setter call

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingSupport.java
- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/ClosureParamTypeInferenceSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9570
> GROOVY-9570: collect context generics starting at innermost class/method

- src/main/java/groovy/lang/MetaClassImpl.java
- src/test/groovy/bugs/Groovy9779.groovy
https://issues.apache.org/jira/browse/GROOVY-9779
> GROOVY-9779: don't chain call properties together

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/STCAssignmentTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9786
> GROOVY-9786: STC: propagate variable assignment tracking for if-else-if chaining

- src/main/java/org/codehaus/groovy/classgen/AsmClassGenerator.java
- src/main/java/org/codehaus/groovy/classgen/asm/sc/StaticTypesCallSiteWriter.java
- src/test/org/codehaus/groovy/classgen/asm/sc/FieldsAndPropertiesStaticCompileTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9791
> GROOVY-9791: SC: no dynamic property method calls for reading/writing protected field from subclass in different package

- subprojects/groovy-console/src/main/groovy/groovy/console/ui/Console.groovy
https://issues.apache.org/jira/browse/GROOVY-9849
Note: The shown elapsed time ≈ compile time + run time
> GROOVY-9849: Show elapsed time in groovy console

- src/main/java/org/apache/groovy/ast/tools/ExpressionUtils.java
- src/test/groovy/transform/stc/FieldsAndPropertiesSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9855
> GROOVY-9855: inline string concat sonner

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/FieldsAndPropertiesSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9882
> GROOVY-9882: add more logic from visitBinaryExpression to visitField

- src/main/java/org/codehaus/groovy/runtime/MetaClassHelper.java
- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingSupport.java
- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/ClosuresSTCTest.groovy
- src/test/groovy/transform/stc/LambdaTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9881
> GROOVY-9881: prefer same parameter count for SAM-type overload selection

- src/main/java/org/codehaus/groovy/transform/ASTTransformationVisitor.java
- src/main/java/org/codehaus/groovy/transform/trait/TraitASTTransformation.java
- src/test/org/codehaus/groovy/transform/traitx/TraitASTTransformationTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9901
https://issues.apache.org/jira/browse/GROOVY-7293
> GROOVY-9901: enable semantic analysis transforms for trait class

- src/main/java/org/codehaus/groovy/vmplugin/v7/IndyInterface.java
https://issues.apache.org/jira/browse/GROOVY-9681
This is a lite version of https://github.com/apache/groovy/pull/1227/files#diff-346370ec8511baf4e07e2c5fd7604a9d163d05d107f3baa4ae2f7809e8e6c759 targeted at 3_0_X specifically (v7.IndyInterface does not exist in master).  The test case is a bit difficult to set up since it requires _indy_ compilation that links to v7.IndyInterface (the Groovy 2.5 part of GROOVY-9681) and execution under Groovy 3.
I am trying this test under Groovy 4 now to see if it needs anything...
> GROOVY-9681: apply GROOVY-9515 patch to v7.IndyInterface

- src/main/java/org/codehaus/groovy/ast/ClassNode.java
- src/test/groovy/bugs/Groovy9906.groovy
https://issues.apache.org/jira/browse/GROOVY-9906
> GROOVY-9906: check index before comparing parameters

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/bugs/Groovy9790.groovy
- src/test/groovy/transform/stc/ClosuresSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9907
> GROOVY-9907: apply parameter/variable instanceof to closure return type

- src/main/java/org/codehaus/groovy/tools/javac/JavaStubGenerator.java
- src/test/org/codehaus/groovy/tools/stubgenerator/Groovy9777.groovy
https://issues.apache.org/jira/browse/GROOVY-9777
> GROOVY-9777: stubgen: add cast for Object parameter in special ctor call

- src/main/java/org/codehaus/groovy/runtime/DefaultGroovyMethods.java
- src/test/groovy/transform/stc/GenericsSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9914
> GROOVY-9914: DGM: add return type parameters for collectEntries variant

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/GenericsSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9915
> GROOVY-9915: use type(s) from static call site to resolve generics

- README.adoc
- buildSrc/src/main/groovy/org.apache.groovy-core.gradle
- src/main/java/org/codehaus/groovy/runtime/DefaultGroovyStaticMethods.java
- src/main/java/org/codehaus/groovy/vmplugin/VMPluginFactory.java
- src/main/java/org/codehaus/groovy/vmplugin/v10/Java10.java
- src/main/java/org/codehaus/groovy/vmplugin/v10/PluginDefaultGroovyMethods.java
- src/main/java/org/codehaus/groovy/vmplugin/v8/Java8.java
- src/main/java/org/codehaus/groovy/vmplugin/v8/PluginDefaultGroovyMethods.java
- src/main/java/org/codehaus/groovy/vmplugin/v9/Java9.java
- src/test/groovy/bugs/Groovy9922.groovy
- subprojects/groovy-binary/build.gradle
https://issues.apache.org/jira/browse/GROOVY-9922
> GROOVY-9922: Add DGM `getPid`

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingSupport.java
- src/test/groovy/transform/stc/TypeInferenceSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9935
> GROOVY-9935: java.lang.Number can accommodate any number type

- src/main/java/org/codehaus/groovy/transform/DelegateASTTransformation.java
- src/main/java/org/codehaus/groovy/transform/trait/TraitComposer.java
- src/test/groovy/transform/stc/BugsSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9938
> GROOVY-9938: SC: inner class needs implicitThis false for method calls

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/GenericsSTCTest.groovy
`inferReturnTypeGenerics` uses first type seen for each placeholder.  If enhanced, `new C<>(1,'b')` could infer `C<Object>` instead of `C<Integer>`.
https://issues.apache.org/jira/browse/GROOVY-9948
> GROOVY-9948: infer type arguments for CCE diamond using argument type(s)

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/TypeInferenceSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9953
> GROOVY-9953: lookup instanceof type for variable on right of binary expression

- src/main/java/org/codehaus/groovy/classgen/asm/InvocationWriter.java
- src/main/java/org/codehaus/groovy/classgen/asm/sc/StaticInvocationWriter.java
- src/main/java/org/codehaus/groovy/classgen/asm/sc/StaticTypesCallSiteWriter.java
- src/test/groovy/transform/stc/FieldsAndPropertiesSTCTest.groovy
- src/test/org/codehaus/groovy/classgen/asm/sc/FieldsAndPropertiesStaticCompileTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9955
> GROOVY-9955: access static fields and invoke static methods using object expression type not owner

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/GenericsSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-6232
https://issues.apache.org/jira/browse/GROOVY-9956
> GROOVY-6232, GROOVY-9956: check LHS type witness for diamond constructor

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/GenericsSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9963
> GROOVY-9963: resolve ctor call diamond for attribute/property expression

- src/main/java/org/codehaus/groovy/control/StaticImportVisitor.java
- src/test/groovy/bugs/Groovy9966.groovy
https://issues.apache.org/jira/browse/GROOVY-9966
> GROOVY-9966: safer object expression transformation

- src/main/java/org/codehaus/groovy/classgen/asm/sc/StaticTypesCallSiteWriter.java
- src/test/groovy/transform/stc/TypeInferenceSTCTest.groovy
- src/test/org/codehaus/groovy/classgen/asm/sc/bugs/Groovy6276Bug.groovy
https://issues.apache.org/jira/browse/GROOVY-9967
> GROOVY-9967: makeGroovyObjectGetPropertySite: leverage property owner

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/ClosureParamTypeInferenceSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9968
> GROOVY-9968: STC ClosureParams: for "T -> Type" use Type not Object

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/GenericsSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9972
> GROOVY-9972: STC: infer ctor call diamond type for ternary branches

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingSupport.java
- src/test/groovy/transform/stc/MethodReferenceTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9974
> GROOVY-9974: extract generics connections: Closure<T> vs SAM return type

- src/main/java/org/codehaus/groovy/classgen/Verifier.java
- src/test/gls/innerClass/InnerClassTest.groovy
https://issues.apache.org/jira/browse/GROOVY-7686
> GROOVY-7686: AIC: place local variable references above super ctor call

- src/main/java/org/codehaus/groovy/classgen/asm/sc/StaticInvocationWriter.java
- src/test/groovy/bugs/Groovy9524.groovy
https://issues.apache.org/jira/browse/GROOVY-9524
> GROOVY-9524: enum const class extends enum class, so no this$0 for calls

- src/main/java/org/codehaus/groovy/tools/javac/JavaStubGenerator.java
- src/test/org/codehaus/groovy/tools/stubgenerator/Groovy7306.groovy
https://issues.apache.org/jira/browse/GROOVY-7306
> GROOVY-7306: stubgen: apply type arguments of super to its constructor parameters

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/LambdaTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9977
> GROOVY-9977: share logic for functional interface assignment

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/FieldsAndPropertiesSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9991
> GROOVY-9991: closure without arrow works for 0 and 1 parameter methods

- src/main/java/org/codehaus/groovy/classgen/InnerClassCompletionVisitor.java
- src/test/groovy/transform/stc/AnonymousInnerClassSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-5728
> GROOVY-5728: anonymous inner class can use private constructor when super is outer

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/GenericsSTCTest.groovy
- src/test/groovy/transform/stc/LambdaTest.groovy
- subprojects/groovy-console/src/main/groovy/groovy/console/ui/ButtonOrTextEditor.groovy
https://issues.apache.org/jira/browse/GROOVY-9995
https://issues.apache.org/jira/browse/GROOVY-9997
> GROOVY-9995: infer ctor call diamond type from closure target type

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/GenericsSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9996
> GROOVY-9996: infer return type generics using declared type of variables

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingSupport.java
- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/ArraysAndCollectionsSTCTest.groovy
- src/test/groovy/transform/stc/ConstructorsSTCTest.groovy
- src/test/groovy/transform/stc/GenericsSTCTest.groovy
- src/test/groovy/transform/stc/MethodCallsSTCTest.groovy
- src/test/groovy/transform/stc/STCExtensionMethodsTest.groovy
- src/test/org/codehaus/groovy/transform/BuilderTransformTest.groovy
https://issues.apache.org/jira/browse/GROOVY-7106
https://issues.apache.org/jira/browse/GROOVY-7274
https://issues.apache.org/jira/browse/GROOVY-8909
https://issues.apache.org/jira/browse/GROOVY-9844
> GROOVY-7106, GROOVY-7274, GROOVY-8909, GROOVY-9844: [] and [:] call args

- src/spec/doc/core-metaprogramming.adoc
> Fix typo in metaprogramming documentation

- src/main/java/org/codehaus/groovy/classgen/asm/ClosureWriter.java
- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/ClosuresSTCTest.groovy
- src/test/groovy/transform/stc/GenericsSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9971
> GROOVY-9971: STC: support "Closure<String> c = { -> return "$v" }"

- src/main/java/org/codehaus/groovy/ast/GenericsType.java
- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/GenericsSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-10010
> GROOVY-10010: check GString element vs String collection for method call

- src/antlr/GroovyLexer.g4
- src/antlr/GroovyParser.g4
- src/main/java/org/apache/groovy/parser/antlr4/AstBuilder.java
- src/test-resources/core/Lambda_01x.groovy
- src/test/groovy/bugs/Groovy4252Bug.groovy
- src/test/groovy/bugs/groovy9236/Groovy9236Bug.groovy
- src/test/groovy/transform/stc/LambdaTest.groovy
https://issues.apache.org/jira/browse/GROOVY-10003
> GROOVY-10003: Eliminate some ambiguities while parsing

- src/main/java/groovy/lang/TracingInterceptor.java
- src/test/groovy/lang/InterceptorTest.groovy
https://issues.apache.org/jira/browse/GROOVY-10009
> GROOVY-10009: TracingInterceptor: "java.lang.Object" for null arguments

- src/main/java/org/codehaus/groovy/ast/tools/WideningCategories.java
- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingSupport.java
- src/test/groovy/transform/stc/GenericsSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-10006
> GROOVY-10006: STC: unify types of multiple type witnesses in method call

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/NamedParameterTest.groovy
https://issues.apache.org/jira/browse/GROOVY-10027
> GROOVY-10027: NamedParam: check against declared/inferred argument type

- src/main/java/org/codehaus/groovy/classgen/AsmClassGenerator.java
- src/test/groovy/MultiDimArraysTest.groovy
https://issues.apache.org/jira/browse/GROOVY-10031
> GROOVY-10031: write NEWARRAY/ANEWARRAY for all single-dimensional arrays

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/GenericsSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-10036
> GROOVY-10036: STC: pass explicit type arguments of extension method call

- src/main/java/org/apache/groovy/ast/tools/ClassNodeUtils.java
- src/main/java/org/codehaus/groovy/classgen/asm/OperandStack.java
- src/main/java/org/codehaus/groovy/runtime/ArrayTypeUtils.java
- src/test/groovy/bugs/Groovy9126.groovy
https://issues.apache.org/jira/browse/GROOVY-10035
> GROOVY-10035: Eliminate redundant type cast

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingSupport.java
- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/GenericsSTCTest.groovy
- src/test/org/codehaus/groovy/classgen/asm/sc/BugsStaticCompileTest.groovy
- subprojects/groovy-ginq/src/main/groovy/org/apache/groovy/ginq/provider/collection/GinqAstWalker.groovy
https://issues.apache.org/jira/browse/GROOVY-9033
> GROOVY-9033: STC: resolve "def list = []" to List<Object> not List<E>

- src/main/java/org/codehaus/groovy/ast/ClassNode.java
- src/test/groovy/bugs/Groovy6938.groovy
- src/test/groovy/bugs/Groovy8310.groovy
- src/test/groovy/bugs/Groovy8609Bug.groovy
- src/test/groovy/bugs/Groovy9338.groovy
- src/test/groovy/transform/stc/ArraysAndCollectionsSTCTest.groovy
- src/test/groovy/transform/stc/BugsSTCTest.groovy
- src/test/groovy/transform/stc/ClosureParamTypeInferenceSTCTest.groovy
- src/test/groovy/transform/stc/ConstructorsSTCTest.groovy
- src/test/groovy/transform/stc/FieldsAndPropertiesSTCTest.groovy
- src/test/groovy/transform/stc/GenericsSTCTest.groovy
- src/test/groovy/transform/stc/LambdaTest.groovy
- src/test/groovy/transform/stc/MethodCallsSTCTest.groovy
- src/test/groovy/transform/stc/STCAssignmentTest.groovy
- src/test/org/codehaus/groovy/ast/tools/GenericsUtilsTest.groovy
- src/test/org/codehaus/groovy/transform/InheritConstructorsTransformTest.groovy
https://issues.apache.org/jira/browse/GROOVY-9800
> GROOVY-9800: ClassNode#toString includes generics of type arguments

- src/spec/doc/_working-with-numbers.adoc
- src/spec/doc/core-syntax.adoc
1. `hash` should be `dash`, right?
2. Should be `java.math.BigDecimal`
> Fix typoes

- src/main/java/org/codehaus/groovy/runtime/metaclass/ClosureMetaClass.java
- src/main/java/org/codehaus/groovy/runtime/metaclass/TransformMetaMethod.java
- src/test/groovy/GroovyInterceptableTest.groovy
https://issues.apache.org/jira/browse/GROOVY-3015
> GROOVY-3015: add GroovyInterceptable check to closure resolve strategy

- subprojects/groovy-console/src/main/groovy/groovy/console/ui/Console.groovy
- subprojects/groovy-console/src/main/groovy/groovy/console/ui/view/MacOSXMenuBar.groovy
Description in https://issues.apache.org/jira/browse/GROOVY-10077
> fix GROOVY-10077

- src/main/java/org/codehaus/groovy/transform/sc/StaticCompilationVisitor.java
- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/gls/invocation/DefaultParamTest.groovy
- src/test/org/codehaus/groovy/classgen/asm/sc/BugsStaticCompileTest.groovy
Before taking on GROOVY-10094, I wanted to take a step back and tidy up a loose end from GROOVY-6851 / GROOVY-9151.
https://issues.apache.org/jira/browse/GROOVY-10104
https://issues.apache.org/jira/browse/GROOVY-10094
https://issues.apache.org/jira/browse/GROOVY-9151
https://issues.apache.org/jira/browse/GROOVY-6851
> GROOVY-6851, GROOVY-9151, GROOVY-10104: SC: skip Verifier generated node

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/transform/stc/ArraysAndCollectionsSTCTest.groovy
size checks as described in 9994 comments
https://issues.apache.org/jira/browse/GROOVY-9985
https://issues.apache.org/jira/browse/GROOVY-9994
https://issues.apache.org/jira/browse/GROOVY-10111
> GROOVY-9985, GROOVY-10111: STC: check array sizes and values not as cast

- src/main/java/org/codehaus/groovy/ast/expr/MethodCallExpression.java
- src/main/java/org/codehaus/groovy/control/StaticImportVisitor.java
- src/test/groovy/bugs/Groovy5239.groovy
This resolves 2 of 3 cases raised by 5239
https://issues.apache.org/jira/browse/GROOVY-5239
> GROOVY-5239: prefer outer class method over static import method

- src/main/java/org/codehaus/groovy/runtime/GroovyCategorySupport.java
- src/test/groovy/CategoryTest.groovy
- subprojects/groovy-xml/src/test/groovy/groovy/xml/GpathSyntaxTestSupport.groovy
https://issues.apache.org/jira/browse/GROOVY-5245
> GROOVY-5245: bean-style property access for boolean "is" category method

- .github/workflows/gradle-snapshot-distribution.yml
- src/test/groovy/bugs/Groovy8678.groovy
after the code review I had the impression that more tests are needed on that
> GROOVY-8678: extend test case

- src/main/java/org/codehaus/groovy/runtime/typehandling/DefaultTypeTransformation.java
- src/test/groovy/bugs/Groovy7867.groovy
Proposed solution to https://issues.apache.org/jira/browse/GROOVY-7867
> GROOVY-7867: cast to collection: attach exception of constructor as suppressed exception

- src/main/java/org/codehaus/groovy/tools/RootLoader.java
https://issues.apache.org/jira/browse/GROOVY-10164
> GROOVY-10164: make RootLoader(ClassLoader) public

- src/main/java/org/apache/groovy/ast/tools/ExpressionUtils.java
- src/test/groovy/bugs/Groovy10191.groovy
https://issues.apache.org/jira/browse/GROOVY-10191
> GROOVY-10191: catch LinkageError during static inline

- src/main/groovy/org/codehaus/groovy/transform/ASTTestTransformation.groovy
- src/test/groovy/bugs/Groovy10199.groovy
https://issues.apache.org/jira/browse/GROOVY-10199
> GROOVY-10199: ASTTest: evaluate with compliation unit's transform loader

- src/main/java/org/codehaus/groovy/runtime/DefaultGroovyMethods.java
- src/main/java/org/codehaus/groovy/runtime/DefaultGroovyMethodsSupport.java
Before I tackle the harder issues of `plus`, I looked over all `T[]` returning methods in `DefaultGroovyMethods` and made minor changes to remove unchecked warnings and return the `self` array type for `minus` and `reverse`.
https://issues.apache.org/jira/browse/GROOVY-6837
> GROOVY-6837: prep work

- src/antlr/GroovyParser.g4
- src/test/org/codehaus/groovy/ast/LineColumnCheck.txt
> Groovy-10520: Capture correct line numbers for Closure block statement.

- src/main/java/org/codehaus/groovy/runtime/DefaultGroovyMethods.java
- src/main/java/org/codehaus/groovy/runtime/ProxyGeneratorAdapter.java
- src/test/org/codehaus/groovy/transform/traitx/TraitASTTransformationTest.groovy
https://issues.apache.org/jira/browse/GROOVY-8243
> GROOVY-8243: support closure for functional interface that extends trait

- src/main/java/org/codehaus/groovy/control/ResolveVisitor.java
- src/test/groovy/bugs/Groovy10587.groovy
https://issues.apache.org/jira/browse/GROOVY-10587
> GROOVY-10587: resolve annotations from module before nested

- src/main/java/org/codehaus/groovy/runtime/DefaultGroovyMethods.java
- src/test/groovy/bugs/Groovy10612.groovy
https://issues.apache.org/jira/browse/GROOVY-10612
> GROOVY-10612: Tweak plus operation for `Map` instance to align with Java

- subprojects/groovy-templates/src/main/groovy/groovy/text/StreamingTemplateEngine.java
- subprojects/groovy-templates/src/test/groovy/groovy/text/StreamingTemplateEngineTest.groovy
https://issues.apache.org/jira/browse/GROOVY-10715
> GROOVY-10715: Make StreamingTemplateEngine support reusing ClassLoader

- .github/workflows/grails-joint-validation.yml
- .github/workflows/groovy-build-dist.yml
- .github/workflows/groovy-build-test-ea.yml
- .github/workflows/groovy-build-test.yml
- .github/workflows/micronaut-joint-validation.yml
Use [gradle-build-action](https://github.com/gradle/gradle-build-action) to speed up build.
> Use gradle-build-action on CI

- settings.gradle
> Bump Gradle Enterprise plugin to 3.11.1

- src/main/java/org/codehaus/groovy/runtime/DefaultGroovyMethods.java
- src/test/groovy/transform/stc/DefaultGroovyMethodsSTCTest.groovy
https://issues.apache.org/jira/browse/GROOVY-7992
https://issues.apache.org/jira/browse/GROOVY-7976
> GROOVY-7992: DGM: `Comparator<? super T>` for comparator parameters

- src/main/java/org/codehaus/groovy/runtime/DefaultGroovyMethods.java
https://issues.apache.org/jira/browse/GROOVY-7919
> GROOVY-7919: add `isCase(Iterable,Object)` for `in` and `!in` support

- src/spec/doc/core-operators.adoc
- src/spec/test/OperatorsTest.groovy
> Minor improvements for Operators documentation

- subprojects/groovy-binary/build.gradle
Follow up #1780, missed renaming this one.
> Rename buildSrc to build-logic

- subprojects/groovy-xml/src/spec/doc/xml-userguide.adoc
> fixed typo

- .gitignore
- gradle.properties
https://docs.gradle.org/7.0.1/release-notes.html#file-system-watching
> Minor tweaks

- src/main/java/org/codehaus/groovy/runtime/ResourceGroovyMethods.java
- src/test/groovy/GroovyMethodsTest.groovy
- subprojects/groovy-nio/src/main/java/org/apache/groovy/nio/extensions/NioExtensions.java
- subprojects/groovy-nio/src/test/groovy/org/apache/groovy/nio/extensions/NioExtensionsTest.groovy
Ref:
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io.path/java.nio.file.-path/extension.html
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io.path/java.nio.file.-path/name-without-extension.html
> GROOVY-10942 Add `extension` & `baseName` extension methods

- build-logic/src/main/groovy/org.apache.groovy-core.gradle
- subprojects/groovy-all/build.gradle
- subprojects/groovy-binary/build.gradle
The deprecation warning that this PR fixes can be seen [in this build scan](https://scans.gradle.com/s/njuvm77j3jark/deprecations?expanded=WyI1OSJd#60)
> Add source dependency on task to fix task cacheability

- subprojects/groovy-groovysh/src/main/groovy/org/apache/groovy/groovysh/commands/ImportCommand.groovy
This PR removes duplicate imports in the repl - that way you can make changes in an interactive way without having to purge all of the imports. Also, it rejects imports which would conflict with existing defined classes - to mirror the new behavior in other contexts.
> GROOVY-11224: Reconsider name duplication for groovysh

- src/main/java/org/codehaus/groovy/classgen/asm/ClosureWriter.java
- src/main/java/org/codehaus/groovy/classgen/asm/sc/StaticTypesLambdaWriter.java
- src/test/groovy/bugs/Groovy11272.groovy
https://issues.apache.org/jira/browse/GROOVY-11272
> GROOVY-11272: Generate `serialVersionUID` for each closure

- subprojects/groovy-groovydoc/src/main/resources/org/codehaus/groovy/tools/groovydoc/gstringTemplates/classLevel/classDocName.html
As per [GROOVY-9464](https://issues.apache.org/jira/browse/GROOVY-9464?jql=project%3DGROOVY%20AND%20id%3DGROOVY-9464 ), groovy doc was made to list inherited properties like inherited fields.
> GROOVY-9464: Made GroovyDoc list inherited properties

- .github/workflows/grails-joint-validation.yml
- .github/workflows/groovy-build-coverage.yml
- .github/workflows/groovy-build-test.yml
- .github/workflows/groovy-rat-check.yml
- .github/workflows/micronaut-joint-validation.yml
https://github.com/gradle/gradle-build-action/releases/tag/v3.0.0-rc.1
> Use gradle/actions/setup-gradle v3

- gradle/wrapper/gradle-wrapper.properties
https://gradle.org/release-checksums/#v8.8
> Add distributionSha256Sum

- src/main/java/org/codehaus/groovy/vmplugin/v9/Java9.java
Reverts [501f7547fd80663eaa17c6504f9c6d1ee3f4bc28](https://github.com/apache/groovy/commit/501f7547fd80663eaa17c6504f9c6d1ee3f4bc28)
If there are other threads blocking this pool groovy might never be able to complete but wait forever.
See https://lists.apache.org/thread/hhxy11oqlpl6phfj945ntxy0c024yd2s
> Do not use common ForkJoinPool on startup

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/ForLoopTest.groovy
- src/test/groovy/transform/stc/LoopsSTCTest.groovy
`for` loop item type for `Class<EnumType>` is `EnumType`
> GROOVY-11597: STC: loop over enum class

- src/main/java/org/codehaus/groovy/classgen/asm/CompileStack.java
- src/main/java/org/codehaus/groovy/classgen/asm/StatementWriter.java
- src/test/groovy/InstanceofTest.groovy
Support this common case in dynamic mode:
```groovy
def x = null
if (x instanceof String s) {
// ...
} else {
s // no such property
}
```
> GROOVY-11229: limit scope of `instanceof` variable

- src/main/java/org/apache/groovy/parser/antlr4/AstBuilder.java
- src/main/java/org/codehaus/groovy/transform/trait/TraitASTTransformation.java
- src/test/groovy/bugs/Groovy11613.groovy
https://issues.apache.org/jira/browse/GROOVY-11613
https://issues.apache.org/jira/browse/GROOVY-11600
> GROOVY-11613: inner class of interface with default methods is static

- subprojects/groovy-ant/src/main/java/org/codehaus/groovy/ant/Groovyc.java
- subprojects/groovy-ant/src/test-resources/org/codehaus/groovy/ant/GroovycTest.xml
https://issues.apache.org/jira/browse/GROOVY-11607
> GROOVY-11607: `groovyc`: `fileset` lists files

- src/main/java/org/codehaus/groovy/classgen/asm/sc/StaticTypesMethodReferenceExpressionWriter.java
- src/test/groovy/transform/stc/MethodReferenceTest.groovy
https://issues.apache.org/jira/browse/GROOVY-11618
https://issues.apache.org/jira/browse/GROOVY-10904
https://issues.apache.org/jira/browse/GROOVY-10741
> GROOVY-10904, GROOVY-11618: reference to inner class property method

- src/main/java/org/codehaus/groovy/runtime/DefaultGroovyMethods.java
- src/test/groovy/groovy/mock/interceptor/MockCallSequenceTest.groovy
remove duplicate words in comment
> chore: remove duplicate words in comment

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingSupport.java
- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/groovy/transform/stc/ReturnsSTCTest.groovy
- src/test/groovy/groovy/transform/stc/TypeInferenceSTCTest.groovy
```groovy
String[] foo() {
['a','b','c' ]
}
```
and
```groovy
@interface A {
String[] value() default []
}
```
> GROOVY-11623: STC: support return of list expression for array method

- src/main/java/groovy/lang/MetaClassImpl.java
- src/main/java/org/codehaus/groovy/transform/sc/transformers/PropertyExpressionTransformer.java
- src/main/java/org/codehaus/groovy/transform/trait/TraitReceiverTransformer.java
- src/test/groovy/org/codehaus/groovy/transform/traitx/TraitASTTransformationTest.groovy
See this comment: https://issues.apache.org/jira/browse/GROOVY-11641?focusedCommentId=17950078&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17950078
> GROOVY-11641: roll back

- build-logic/src/main/groovy/org.apache.groovy-asciidoctor.gradle
- src/bin/groovydoc_completion
- subprojects/groovy-ant/src/main/java/org/codehaus/groovy/ant/Groovydoc.java
- subprojects/groovy-groovydoc/src/main/groovy/org/codehaus/groovy/tools/groovydoc/Main.groovy
- subprojects/groovy-groovydoc/src/main/java/org/codehaus/groovy/tools/groovydoc/GroovyDocTool.java
- subprojects/groovy-groovydoc/src/main/resources/org/codehaus/groovy/tools/groovydoc/Main.properties
- subprojects/groovy-groovydoc/src/spec/doc/groovydoc.adoc
- subprojects/groovy-groovydoc/src/test/groovy/org/codehaus/groovy/tools/groovydoc/GroovyDocTest.java
- subprojects/groovy-groovydoc/src/test/groovy/org/codehaus/groovy/tools/groovydoc/GroovyDocToolTest.java
- subprojects/groovy-groovydoc/src/test/resources/groovydoc/groovyDocTests.xml
See https://lists.apache.org/thread/gvjw8rnnw3ntd9v8gh0h3xsn85qfbt3x for context
> GROOVY-11668: Support specifying the Java source file version for groovydoc

- src/main/java/groovy/lang/MetaClassImpl.java
- src/main/java/groovy/lang/MissingMethodException.java
- src/spec/test/typing/StaticCompilationIntroTest.groovy
- src/test/groovy/bugs/Groovy3645.groovy
- src/test/groovy/bugs/Groovy4857.groovy
- src/test/groovy/bugs/Groovy6072.groovy
- src/test/groovy/bugs/Groovy8678.groovy
- src/test/groovy/bugs/Groovy9779.groovy
- src/test/groovy/bugs/MethodClosureTest.groovy
- src/test/groovy/groovy/ThisAndSuperTest.groovy
- src/test/groovy/groovy/util/BuilderSupportTest.groovy
- src/test/groovy/org/codehaus/groovy/transform/NewifyTransformBlackBoxTest.groovy
> GROOVY-11676: object expression type in `MethodClosure` error message

- src/main/java/org/codehaus/groovy/vmplugin/v8/CacheableCallSite.java
- src/main/java/org/codehaus/groovy/vmplugin/v8/IndyInterface.java
https://issues.apache.org/jira/browse/GROOVY-11640
> GROOVY-11640: GC pause by Metadata GC Threshold for weeks then turned to Full GC

- src/main/java/org/codehaus/groovy/classgen/AsmClassGenerator.java
- subprojects/groovy-ginq/src/main/groovy/org/apache/groovy/ginq/provider/collection/GinqAstWalker.groovy
https://issues.apache.org/jira/browse/GROOVY-11703
> GROOVY-11703: Fails to compile due to forbidden access to `this` of interface

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingSupport.java
- src/test/groovy/groovy/transform/stc/ArraysAndCollectionsSTCTest.groovy
> GROOVY-11659: STC: support assigning of collection to primitive array

- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingSupport.java
- src/main/java/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java
- src/test/groovy/groovy/transform/stc/BugsSTCTest.groovy
- subprojects/groovy-ginq/src/main/groovy/org/apache/groovy/ginq/provider/collection/runtime/NamedRecord.groovy
- subprojects/groovy-ginq/src/main/groovy/org/apache/groovy/ginq/provider/collection/runtime/NamedTuple.groovy
move GROOVY-11341 to lower clause (differing declaring classes)
> GROOVY-11746: retain accessible synthetic override
